name: CMake

on:
  push:
    branches: [ master ]
    paths: [ CMakeLists.txt, 'src/**', 'd2mapapi/**', 'common/**', 'tools/**', 'json/**', 'inih/**' ]
  pull_request:
    branches: [ master ]
    paths: [ CMakeLists.txt, 'src/**', 'd2mapapi/**', 'common/**', 'tools/**', 'json/**', 'inih/**' ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: CMake Configure
      run: cmake -B ${{github.workspace}}/build -G "Visual Studio 16 2019" -A Win32 -DUSE_STATIC_CRT=ON

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target snapshot-pack

    - uses: actions/upload-artifact@v2
      with: 
        name: D2RMH-snapshot
        path: |
          ${{github.workspace}}/build/bin/D2RMH-snapshot.zip
        retention-days: 7